CREATE TABLE FAN (
    USERNAME VARCHAR(60) NOT NULL PRIMARY KEY,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD CHAR(60) NOT NULL,
    PROFILE_PICTURE VARCHAR(70),
    BIO VARCHAR(500),
    ROLE_TYPE VARCHAR(11)
);