CREATE TABLE FAN (
    USERNAME VARCHAR(60) NOT NULL PRIMARY KEY,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD CHAR(60) NOT NULL,
    PROFILE_PICTURE VARCHAR(70),
    BIO VARCHAR(500),
    ROLE_TYPE VARCHAR(11)
);

CREATE TABLE CHAT_MESSAGE (
    ID CHAR(36) PRIMARY KEY,
    SENDER VARCHAR(60) NOT NULL,
    MESSAGE VARCHAR(300) NOT NULL,
    TIMESTAMP TIMESTAMP NOT NULL
);